cuda_num="2"
batch_size=1
use_val=true

[data_config]
contain_bj=false
drop_short=false
short_len=60
time_step=30
stock_sample_time=3
stock_sample_num=300
mask_sample_time=1
temporal_mask_ratio=0.3
graph_mask_ratio=0.3
graph_type='industry'


[train_config]
model_save_folder='./result/model_1/'
epochs=100
device='cuda'
temporal_reg_loss_weight=1
graph_reg_loss_weight=0.2
graph_mse_loss_weight=0.2
subgraph_loss_weight=0.1
lr_rate=1e-4

[model_config]
time_step=30
input_dim=45
input_embedding_temporal_hidden_dim=128
input_embedding_temporal_out_dim=64
gat_output_dim=32
num_head=4
gat_1_dropout=0.7

transformer_encoder_hidden_dim=512
transformer_encoder_output_dim=256
transformer_encoder_head_num=4
transformer_encoder_use_mask=true

transformer_decoder_hidden_dim=256
transformer_decoder_output_dim=128
transformer_decoder_head_num=4
transformer_decoder_use_mask=true

gen_graph_hidden_dim=128

output_hidden_dim=128


