cuda_num="3"
batch_size=1
use_val=true
use_test=true
pretrain_model_path="./result/model_1/"
pretrain_model_file_name="model.pt"
model_name='mlp'

[data_config]
data_type="ch_daily_processed"
stock_list="csi300"
start_date="2010-01-01"
end_date="2022-12-31"
contain_bj=false
drop_short=false
short_len=200
time_step=30
val_begin="2021-01-01"
test_begin="2023-01-01"
stock_sample_time=1
stock_sample_num=300
mask_sample_time=1
temporal_mask_ratio=0
graph_mask_ratio=0
graph_type='industry'

[mlp_model_config]
time_step=30
num_head=4
transformer_encoder_output_dim=256
predict_gat_output_dim=128
score_hidden_dim=64
predict_gat_dropout=0.1
fc_layer_1_output_dim=256
fc_layer_2_output_dim=128


[train_config]
model_save_folder='./result/model_1/'
epochs=100
device='cuda'
lr_rate=1e-4
model_name="mlp_model.pt"
best_model_name="best_mlp_model.pt"
loss_name="mlp_model_loss.png"
